# Generated by Django 4.2.7 on 2025-09-30 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "board",
                    models.JSONField(
                        default=list, help_text="Game board state (9 elements)"
                    ),
                ),
                (
                    "current_player",
                    models.CharField(
                        choices=[("X", "Player X"), ("O", "Player O")],
                        default="X",
                        help_text="Current player's turn",
                        max_length=1,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "In Progress"),
                            ("x_wins", "X Wins"),
                            ("o_wins", "O Wins"),
                            ("draw", "Draw"),
                        ],
                        default="in_progress",
                        help_text="Current game status",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Tic-Tac-Toe Game",
                "verbose_name_plural": "Tic-Tac-Toe Games",
                "ordering": ["-created_at"],
            },
        ),
    ]
